### ISSUE TITLE
loop does not work me

### ISSUE THREAD

**Issue by newmesiss** [erost/ng-videosharing-embed#28]
option does not work on youtube repeat, I am using the following

            <embed-video class="embed-responsive-item" loop=1 autoplay=1 data-ng-href="{{rec.video}}"  controls=0 ></embed-video>

**Comment by erost** [comment]
Hi newmesiss,
you can see the root cause of the issue here: https://developers.google.com/youtube/player_parameters#loop

For a loop to work, a playlist parameter is needed.
I put additional code in the directive so that when there is a loop and no playlist, the current video is used to create the missing parameter.

**Comment by newmesiss** [comment]
That means that if only a video can not be repeated?

**Comment by erost** [comment]
It can.
But due to how Youtube implemented the parameter, it will only loop on a playlist. 
With the latest code addition, if you set loop=1 and no playlist, the directive will automatically create a single item playlist with the video you want to loop on.

**Comment by newmesiss** [comment]
perfecto , gracias
